name: Feature request
description: Suggest an idea for flamegpu2
title: "[Feature]: "
body:
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "e.g. I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Describe the solution you'd like"
      description: A clear and concise description of what the problem is.
      placeholder:
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Is your feature request related to a problem?
      description: "A clear and concise description of any alternative solutions or features you've considered"
      placeholder:
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder:
    validations:
      required: false
  
